apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgres
data:
  DB_NAME: postgres
  DB_USER: postgres
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  DB_PASSWORD: <OUTPUT OF `echo -n 'the password' | base64`>